# Generated by Django 3.2.22 on 2023-10-06 00:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbCategoryProduct',
            new_name='CategoryProduct',
        ),
        migrations.RenameModel(
            old_name='tbInventoryProduct',
            new_name='InventoryProduct',
        ),
        migrations.RenameModel(
            old_name='tbProduct',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='tbRateProduct',
            new_name='RateProduct',
        ),
        migrations.RenameModel(
            old_name='tbSizeProduct',
            new_name='SizeProduct',
        ),
    ]
